# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4237ae67ecda9021942b3efb2c42679e1c59813b5947bf863ac6a73ce9491014362d9a0840810428325466b46090743ea052475f9601842da42d15c07dfd2e9

test:
  secret_key_base: 9f920d8719323cc958f30f4dae3416a87b8e6b8d8d7ac8778d70d20d60beee4a28aac458216283052694eba72311208642230389560dddf6d2d5c9ee75cccea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
